import type { Blog } from "@/types/blog";

export const sampleBlogs: Blog[] = [
    {
        $id: "sample-blog-1",
        title: "How I Built My First Next.js App",
        slug: "how-i-built-my-first-next-js-app",
        content: "The first version was messy, but every rough edge taught me something about routing, rendering, and building a product people can actually use.",
        extraContent: "A practical first-project journal for developers finding their rhythm.",
        tags: JSON.stringify(["nextjs", "javascript"]),
        status: "published",
        createdAt: "2026-09-18T09:00:00.000Z",
        updatedAt: "2026-09-18T09:00:00.000Z",
    },
    {
        $id: "sample-blog-2",
        title: "A Calm Introduction to Appwrite TablesDB",
        slug: "a-calm-introduction-to-appwrite-tablesdb",
        content: "TablesDB makes the boundary between your data model and your application much easier to see. Here is the mental model that helped me get started.",
        extraContent: "Rows, permissions, and the small decisions that make a backend easier to trust.",
        tags: JSON.stringify(["appwrite", "backend"]),
        status: "published",
        createdAt: "2026-09-15T09:00:00.000Z",
        updatedAt: "2026-09-15T09:00:00.000Z",
    },
    {
        $id: "sample-blog-3",
        title: "Designing Interfaces That Feel Like Home",
        slug: "designing-interfaces-that-feel-like-home",
        content: "Good interface design is less about adding more and more about making the next useful action feel obvious, comfortable, and worth taking.",
        extraContent: "Notes on hierarchy, rhythm, and building spaces people want to return to.",
        tags: JSON.stringify(["design", "frontend"]),
        status: "published",
        createdAt: "2026-09-11T09:00:00.000Z",
        updatedAt: "2026-09-11T09:00:00.000Z",
    },
    {
        $id: "sample-blog-4",
        title: "The Small Habits Behind Better Code",
        slug: "the-small-habits-behind-better-code",
        content: "Readable code rarely comes from one heroic refactor. It comes from small habits: naming things well, testing the edge, and leaving the next person a clear path.",
        extraContent: "A short list of habits that compound over time.",
        tags: JSON.stringify(["engineering", "workflow"]),
        status: "published",
        createdAt: "2026-09-07T09:00:00.000Z",
        updatedAt: "2026-09-07T09:00:00.000Z",
    },
    {
        $id: "sample-blog-5",
        title: "Learning in Public Without Losing Your Voice",
        slug: "learning-in-public-without-losing-your-voice",
        content: "Sharing the work while you are still learning creates useful conversations. The trick is to be specific about what you know, what you do not, and what you are trying next.",
        extraContent: "Why honest progress notes often become the most useful technical writing.",
        tags: JSON.stringify(["community", "writing"]),
        status: "published",
        createdAt: "2026-09-03T09:00:00.000Z",
        updatedAt: "2026-09-03T09:00:00.000Z",
    },
];